### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by oryan2** [funjack/launchcontrol#22]
I have the blender plugin installed and enabled but I don't see it in the interface. Does it need to be added somehow?

**Comment by funjack** [comment]
Sorry to hear you are having trouble. I do need a little bit more information in order to help your. Which plugin are you having trouble with:
- Blender
- Kodi
- VLC

If it's the Funscripting Blender addon, then you probably not downloaded correctly (github/browsers downloads can be a bit tricky.) Check out this post for the details: http://www.realtouchscripts.com/viewtopic.php?p=11772#p11772

**Comment by oryan2** [comment]
Thank you for your reply, I actually found the answer to my question in that very thread the other day. As mentioned, when you import a video into blender, by default, both the video and audio are highlighted. As soon as I right clicked on the video only bar, the plugin appeared and I had no issues creating a really good script. That brings me to my next question. Is there a good place to share and find custom videos along with scripts? I'm not really interested in the "Hero" scripts, I'm more interested in actual synced up porn. I would love to share the script I made with the "Funscripting" addon. Thanks again!

**Comment by funjack** [comment]
I'm glad to hear that it worked out for you.

As for the sharing stuff, video+script sharing together can be hard due to copyright. Putting a script up somewhere should not be too hard, and just link to a video source (eg pornhub link or something.)

The http://www.realtouchscripts.com/ forum is probably the best place to put up scripts or ask about sharing, since it already used for exchanging RT and Vorze scripts. You do need to change to file extension to something like .txt in order for them to allow it as an attachment though.

If you are familiar with git you can put your script in a PR for https://github.com/funjack/funscripts but I can understand if that is too technical :)
